// This file is auto-generated by FlutterFire CLI.
// Replace with your own Firebase project configuration.
// Run: flutterfire configure
// Or manually create a Firebase project and add your config here.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project configuration
  // Get these values from: https://console.firebase.google.com
  // 1. Create a Firebase project
  // 2. Add Android app (package: com.colorbynumber.color_by_number)
  // 3. Add iOS app (bundle ID: com.colorbynumber.colorByNumber)
  // 4. Download google-services.json (Android) and GoogleService-Info.plist (iOS)
  // 5. Replace the placeholder values below

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8assugQUV1iQvNXcZ8q5zrWDdhLJV5o',
    appId: '1:29712384770:android:3bb38aa5e6fa61bfb6f81b',
    messagingSenderId: '29712384770',
    projectId: 'coloring-game-f1292',
    databaseURL: 'https://coloring-game-f1292-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coloring-game-f1292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY-HERE', // GoogleService-Info.plist dosyasındaki API_KEY değeri
    appId: 'YOUR-IOS-APP-ID-HERE',   // iOS uygulaması eklenince burası dolacak
    messagingSenderId: '29712384770',
    projectId: 'coloring-game-f1292',
    databaseURL: 'https://coloring-game-f1292-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coloring-game-f1292.firebasestorage.app',
    iosBundleId: 'com.colorbynumber.colorByNumber',
  );
}
